### PR TITLE
Venue Page: Removing Iframe loading of Google map.

### PR DESCRIPTION
**Pull request by ultimatecoder**
[IMP] Venue Page: Removing Iframe loading of Google map to save the page loading speed. Adding link of Google Map, Email, Phone to the address of the University. Improving view.

### CODE REVIEW

**Comment by ultimatecoder** [comment]
@Dhavan  Hey brother will you review and merge it? I have updated the venue page view.

**Comment by codingquark** [comment]
@ultimatecoder Now you need to review it.
Also, do you think the Map link should be _blank?

**Comment by ultimatecoder** [comment]
@Dhavan  :+1: Let me change the _blank things. I found comment like this will be more readable on code at particular line. Actual code review :page_with_curl:

**Comment by ultimatecoder** [comment]
@Dhavan  Reminding you to review this branch.

**Pull request merged**
